### ISSUE TITLE
Update Syllabus Logistics and Social items

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/emory-camp#5]
https://docs.google.com/document/d/1nCc2oCg4QYawSI76nB6B44oCI7O1SA-mUN0iwHN14uA/edit#

- [x] Add Monday morning rendezvous and/or transportation info
- [x] Add group lunch and tour info to appropriate day
- [x] Remove maps and links that reference UCSB (usually in lunch and dinner sections)
- [x] Provide link to map or list of lunch options
- [x] Add morning breakfast/coffee info - i.e. will it be provided or should folks bring their own
- [x] Update Friday link to point to Code4Lib regional meet up information

See this link for logistics details https://docs.google.com/spreadsheets/d/1pi26xuJD33TlEW40t0wR7UbqMJNdLAHz4ZOWicioHo4/edit#gid=0

**Comment by RachelDCE** [comment]
I have completed all the tasks in this issue/the Google Doc has been updated
